// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYno6WG9yxv6KNDjbNyJ9MPLF51TAus4',
    appId: '1:244500002147:android:92fabd63007b71935bcf56',
    messagingSenderId: '244500002147',
    projectId: 'fasum-apps-axel',
    databaseURL: 'https://fasum-apps-axel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-apps-axel.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgkHI71y2xKcdvIskRYnszEnO6kS-T9E',
    appId: '1:244500002147:web:1dadbff9debb11535bcf56',
    messagingSenderId: '244500002147',
    projectId: 'fasum-apps-axel',
    authDomain: 'fasum-apps-axel.firebaseapp.com',
    databaseURL: 'https://fasum-apps-axel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-apps-axel.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgkHI71y2xKcdvIskRYnszEnO6kS-T9E',
    appId: '1:244500002147:web:47df37db4ee2874f5bcf56',
    messagingSenderId: '244500002147',
    projectId: 'fasum-apps-axel',
    authDomain: 'fasum-apps-axel.firebaseapp.com',
    databaseURL: 'https://fasum-apps-axel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-apps-axel.firebasestorage.app',
  );

}